### ISSUE TITLE
Refactor data model and Toggl implementation to allow for other workspaces

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#136]
- API key and workspace ID are currently environment variables

**Comment by mecoccaro** [comment]
@otech47 Right now we get the workspaceID from the toggl url so we can delete that environment variable, the API key is needed so we can fetch the time entries of a project.

**Comment by otech47** [comment]
@mecoccaro be sure the environment variable is not used in any other parts of the code before deleting it please

**Comment by mecoccaro** [comment]
Opening a new PR for deleting from `constants.js` the constant `WORKSPACE_ID` that is never used in the project.
