### ISSUE TITLE
Implement authenticated access to clients and projects

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#238]
Use the Permissions table to check first whether the Contributor that is logged in has access to the project or client before returning a list to the browser

When a Client or a Project is created, a Permission should also be added with the ID of the Contributor creating it

**Comment by otech47** [comment]
We also need a migration script to populate Permissions for existing Clients and Projects

**Comment by sofiarm21** [comment]
**Note:** adding client_id into the `permissions table?
