### ISSUE TITLE
Client Overview page colors bug

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/trinary#252]
**Describe the bug**

1. What did you do? I created a new client and got redirected to `http://localhost:6002/clients/2`
2. What did you expect to happen? See the client overview page as normal
3. What happened instead? The client overview page was rendered but with different colors

**Screenshots**
<img width="1440" alt="Screen Shot 2021-01-27 at 9 04 17 AM" src="https://user-images.githubusercontent.com/49292858/105995115-edff2800-607e-11eb-9546-b8196bed400d.png">

**OS/Browser:**
- [ ] iOS
- [ ] Windows
- [ ] Chrome
- [x] Safari
- [x] Mac
- [ ] Firefox
- [ ] Android
- [ ] Tablet
- [ ] Mobile
- [x] Desktop

**Comment by Ovifer13** [comment]
This bug has never happened to me

**Comment by otech47** [comment]
I couldn't reproduce either so maybe it is resolved
