### ISSUE TITLE
Fix UI responsiveness across the app

### ISSUE THREAD

**Issue by sofiarm21** [setlife-network/trinary#253]

**Comment by otech47** [comment]
Adding a max-width somewhere on a container that is at a high level in the DOM I think would help improve UI on ultra-wide screens/desktops:

![Screen Shot 2021-02-09 at 8 04 29 AM](https://user-images.githubusercontent.com/4914611/107367554-71703e80-6aad-11eb-9b6f-833350c51e1b.png)
