### ISSUE TITLE
Do research and testing on sequelize mutations from heroku deploys

### ISSUE THREAD

**Issue by sofiarm21** [setlife-network/trinary#320]
Some resources:
* https://devcenter.heroku.com/articles/nodejs-support#heroku-specific-build-steps
* https://devcenter.heroku.com/changelog-items/1557
* https://help.heroku.com/CTFS2TJK/how-do-i-run-multiple-processes-on-a-dyno

**Comment by sofiarm21** [comment]
Currently using `heroku-cleanup` to run `npx sequelize-cli db:migrate` on Heroku deploy pipeline after build

**Comment by otech47** [comment]
@sofiarm21 I suggest `heroku-prebuild` also a bit more universal and less heroku-specific (in case we deploy in a different environment in the future) would be simply with `prebuild`

I've tested this solution with another project before too so it definitely should work

```
"start-server": "node server.js",
"prebuild": "node -e \"require('./api/database').migrate()\"",
"build": "react-scripts build",
```

**Comment by otech47** [comment]
NPM would be the more universal option: https://docs.npmjs.com/cli/v7/using-npm/scripts#pre--post-scripts

**Comment by sofiarm21** [comment]
After some tests thesis what I found

* `heroku-cleanup` is called after build and does work for running migrations, but this step is usually for cleaning cache so not recommended
* `heroku-postbuild` runs the migrations but the `build` script will not run so It doesn't work
* `heroku-prebuild` doesn't work because when it's ruined the dependencies are not installed yet, but `prebuild ` only does work

<img width="1440" alt="Screen Shot 2021-02-18 at 6 03 11 PM" src="https://user-images.githubusercontent.com/49292858/108512846-2d90ec80-7298-11eb-85b6-1158bc414424.png">

<img width="1440" alt="Screen Shot 2021-02-19 at 9 46 22 AM" src="https://user-images.githubusercontent.com/49292858/108512812-210c9400-7298-11eb-8e34-5ca2a96fc7c2.png">

*  run `sequelize-cli` commands with `npm` doesn't seems to work
