### ISSUE TITLE
Add sats to the list of currencies in all data fields

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#362]
100,000,000 sats = 1 BTC

Since 1 bitcoin is growing in value, it's more realistic to set the budget for smaller projects as 6,000,000 sats instead of 0.06 BTC

The symbol can just be $ if it's easiest unless you can find a creative alternative

**Comment by sofiarm21** [comment]
@otech47 Is this a replacement of the Bitcoin option, or ca we have both (SAT and BTC)?
