### ISSUE TITLE
Contributor detail page crashing in production

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#368]
https://user-images.githubusercontent.com/4914611/111317246-59ef1d00-863a-11eb-9af3-6e8660bfc7b0.MP4

**Comment by otech47** [comment]
Also the `/projects/1/contributors` crashes for some unknown condition

![Screen Shot 2021-03-16 at 11 00 29 AM](https://user-images.githubusercontent.com/4914611/111331034-e4d61480-8646-11eb-88d9-4b5e69bbd18f.png)

**Comment by sofiarm21** [comment]
> Also the `/projects/1/contributors` crashes for some unknown condition
> 
> ![Screen Shot 2021-03-16 at 11 00 29 AM](https://user-images.githubusercontent.com/4914611/111331034-e4d61480-8646-11eb-88d9-4b5e69bbd18f.png)

@otech47 It seems working for me
<img width="1440" alt="Screen Shot 2021-03-31 at 11 35 17 AM" src="https://user-images.githubusercontent.com/49292858/113171181-3a98e800-9215-11eb-8914-e835afc1f901.png">

**Comment by otech47** [comment]
@sofiarm21 let us know if you're still working on this or maybe @mecoccaro can help debug

**Comment by sofiarm21** [comment]
@otech47 
Update on the bug:
- It seems that the allocation tile is causing the crash
- I was only able to reproduce it for contributor 1 `https://trinary.setlife.tech/contributor/1` 
- Could be triggered by inconsistent data on the DB, already asked for the DB keys for further debugging
I will keep testing

**Comment by sofiarm21** [comment]
The bug is caused because of the lack of currency in some of the DB entires
![Screen Shot 2021-07-02 at 1 59 12 AM](https://user-images.githubusercontent.com/49292858/124227723-2052fc80-dad9-11eb-8e7b-51fb6e558d98.png)
