### ISSUE TITLE
'Add Client' Page Bug

### ISSUE THREAD

**Issue by daaveed** [setlife-network/trinary#385]
**Describe the bug**
A clear and concise description of what the bug is by answering the following questions with as much detail as possibe

1. I opened the app, from the client list page I navigated to the project list page. Then I clicked on the TS App Upgrade button and entered that project overview page. Then I clicked on the home button (SetLife button). Then I clicked on 'create a client' button.
2. I expected the client creation page to be empty.
3. At the head of the page, there was the header, 'TS App Upgrade'. As if I was still in that project overview page.

This bug was consistent with every single project title that I went through while repeating this process.

**Screenshots**
<img width="1276" alt="Screen Shot 2021-04-06 at 11 37 15 AM" src="https://user-images.githubusercontent.com/41223034/113746963-82fc4e00-96cc-11eb-9f10-9856e75c3b92.png">

Tested on Chrome.

**Comment by sofiarm21** [comment]
@otech47  Not being able to reproduce this, unless anyone had been experimenting a similar bug this could be closed
