### ISSUE TITLE
Create a webhook endpoint for syncing Stripe Invoices with Trinary Payments

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#401]
- The `external_uuid` should be prefixed with `STRIPE_` OR add a new column `external_uuid_type`? (possible values are `stripe` and `invoicely`) to distinguish between Stripe-linked data
- For the `date_incurred` property see if it's possible to get the timestamp when it was sent (see screenshot for possible events to listen to)
<img width="846" alt="Screen Shot 2021-04-16 at 11 28 25 AM" src="https://user-images.githubusercontent.com/4914611/115055305-e7769480-9ea6-11eb-9f94-d11ac1e11180.png">
- When the Stripe Invoice is paid, we want to update the Trinary Payment with the correct `date_paid` field
- Use the Stripe `customer_id` to find the Trinary Client for the Payment's `client_id`
- Consider whether this webhook should do a full check for invoices on all Customers or if it should only push the invoice that triggered the webhook event

**Comment by sofiarm21** [comment]
Discuss: The webhook should be triggered when the payment is `created` or `sent`?

**Comment by sofiarm21** [comment]
@otech47 looking at this issue it seems it can be closed, I misspelled the `closes` keyword
