### ISSUE TITLE
Create Stripe Invoices when a Payment is added manually

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#402]
- Should we create the Stripe Invoice first and let the webhook create the Trinary Payment? 
- A placeholder product ID will be used to create new Prices for the amount the user submits for the Payment
<img width="1843" alt="Screen Shot 2021-04-16 at 11 42 16 AM" src="https://user-images.githubusercontent.com/4914611/115056952-0e35ca80-9ea9-11eb-8422-a6da72a950ab.png">

**Comment by otech47** [comment]
Placeholder product ID: https://dashboard.stripe.com/test/products/prod_JJXofAMeGR4HIS

**Comment by sofiarm21** [comment]
<img width="835" alt="Screen Shot 2021-07-09 at 12 13 32 AM" src="https://user-images.githubusercontent.com/49292858/125022355-82b47b80-e04a-11eb-8231-ab670bc2e458.png">
