### ISSUE TITLE
Fix various allocation bugs

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#411]
https://www.loom.com/share/ce9b825216cd462f9b3b6460c0dcd005

- [x] Sort payments to select from in an allocation by Date Incurred (most recent first)
- [x] When adding an allocation it says $0.00 allocated until refreshing
- [x] Can't edit the hourly rate of an existing allocation (edit button is disabled)
- [x] When trying to edit an allocation the Hours per week calculations do not update properly (in add allocation they do update properly)
- [x] Delete button click listening area is overlapping on top of Edit, should be moved it over to the right

(not shown in video)
- [x] When deleting an allocation from the Project Payments page, it does not disappear from the list until after refreshing the page
- [x] When opening a payment on the Project Payments page to edit an allocation, it is not clear that the allocation can be clicked on. Improve this UI with some indication that you can edit the allocation as well as the payment with separate buttons?

**Comment by Ovifer13** [comment]
Task 2: _When adding an allocation it says $0.00 allocated until refreshing_ was already fixed on Issue #453
