### ISSUE TITLE
Add environment handling for all Stripe API functionality

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#420]
Make sure that when `CUSTOM_ENV=staging` vs `CUSTOM_ENV=production`, there is logic in place with regards to the Stripe keys used on the Trinary API and the webhook URLs configured in Stripe respecting each environment

```
Test Mode => https://trinary-staging.setlife.tech
Live Mode => https://trinary.setlife.tech
```

**Comment by mecoccaro** [comment]
The enviroment variblaes are set on each pipeline using Stripe keys on each case.
