### ISSUE TITLE
Add error handling for large expected_budget overflow errors

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#425]
If you create a new project with an expected budget of 100,000,000 (100 million) the project will fail to create because of 32-bit integer limitations with GraphQL

Even better would be to support > 32-bit integers but this issue is just for validating and indicating to the user the max value of the field

**Comment by otech47** [comment]
https://github.com/Nberezhnoy/apollo-type-bigint#readme

**Comment by sofiarm21** [comment]
@otech47 This can be closed

**Comment by sofiarm21** [comment]
`message: "Variable \"$expected_budget\" got invalid value 100000000000; Int cannot represent non 32-bit signed integer value: 100000000000"`

**Comment by sofiarm21** [comment]
Fix this when creating/editing a project. Also check another inputs as allocations
