### ISSUE TITLE
Containerize the project with Docker

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#446]
Create a Dockerfile for frontend, backend, and/or both

**Comment by sofiarm21** [comment]
@otech47 Never done this before but it seems interesting so I will assign myself and keep everyone updated on how It goes

**Comment by otech47** [comment]
@sofiarm21 check the Dockerfile on Careerscore for an example

**Comment by otech47** [comment]
- Combine the 2 Dockerfiles into 1 `/dockerfiles/Dockerfile-deploy`
- Create a new `Dockerfile-develop` (uses `npm run ui` instead of `npm run build` and also starts the web server with `node server`)

As a developer, I want to be be able to clone the repo from scratch and run a set of docker commands that set up the development environment without having to use `npm` commands. (Do we need `docker-compose` for this?)

As a system administrator, I want to be able to deploy the app to Heroku and see that the Dockerfile is used to build and deploy the application. (see https://devcenter.heroku.com/articles/build-docker-images-heroku-yml)

**Comment by otech47** [comment]
@sofiarm21  not sure if you saw this already

https://engageinteractive.co.uk/blog/making-docker-faster-on-mac
