### ISSUE TITLE
Many create/update/delete functions do not reflect in UI until you refresh the page

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#453]
Tried with:

- Deleting allocations
- Creating clients and clicking the Home logo in nav
- Creating projects and clicking the Home logo in nav

There might be several other places so we should test all create/update/delete functions throughout the entire UI and make sure it updates the local state and does not require a refresh

**Comment by Ovifer13** [comment]
https://github.com/trojanowski/react-apollo-hooks/issues/158

**Comment by Ovifer13** [comment]
- [ ] Creating Clients.
- [ ] Creating Projects.
- [ ] Deleting Allocations.
- [ ] Creating a contributor is not updating Payments.
