### ISSUE TITLE
Editing an Allocation allows letters and special characters on numeric fields

### ISSUE THREAD

**Issue by Ovifer13** [setlife-network/trinary#480]
**Describe the bug**
In a project payment where you can see the allocations, if you choose to edit one, you can type letters and special characters inside fields that are supposed to only accept numbers. Only the total amount field on max budget won't let me type anything that is not a number.

**Screenshots**
**Prorated Monthly**
![image](https://user-images.githubusercontent.com/86666889/126813723-747a7a83-6aae-4dd6-9b80-6cd3b1345d5d.png)

**Max Budget**
![image](https://user-images.githubusercontent.com/86666889/126813856-b873e645-bfa7-424c-b992-4e57350cb8f9.png)

If you click on Edit it will save the incorrect inputs and the allocation will look as follows.
![image](https://user-images.githubusercontent.com/86666889/126814079-38bec312-a5a6-416d-90b9-0f4e634728e3.png)

**Comment by otech47** [comment]
Yeah we should have validation functions that run on those fields every time they change so that only safe number values can be input there

**Comment by otech47** [comment]
I know this can be done with redux-form but there may be other ways

https://redux-form.com/6.5.0/examples/material-ui/

And @sofiarm21 should know better where these fields are exactly but found one here:

https://github.com/setlife-network/trinary/blob/develop/src/components/RateMaxBudgetForm.js
