### ISSUE TITLE
Optional Chaining on budgeting module bug

### ISSUE THREAD

**Issue by mecoccaro** [setlife-network/trinary#519]
We need to check NodeJS versions because optional chaining on the budgeting module is causing an error on compile time in the server.

Error example
![imagen](https://user-images.githubusercontent.com/36824674/132442372-df161ded-0962-4d9d-9447-7bbca95a2eb5.png)

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by sofiarm21** [comment]
@mecoccaro you were able to resolve this by using the nvm manager on your computer?

**Comment by mecoccaro** [comment]
@sofiarm21 Yes!! nvm works perfect, I just changed to node version 14.17.6 and the error is gone.
