### ISSUE TITLE
Check Github handle changes upon login

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#567]
- When a user logs in with Github and the API checks the Contributors table to see if it exists, we need to make sure we use the Github UUID instead of the handle so that we recognize existing users who have changed their handle and update the Contributors table upon logging in

**Comment by Ovifer13** [comment]
The system already search contributors in the table using the github_id
![image](https://user-images.githubusercontent.com/86666889/143257628-b024f55d-6a4f-4b16-856b-f5717155e1b5.png)

We just have to check after the github_id if the github_handle of that user is different and if It's different we update the table

**Comment by Ovifer13** [comment]
In `server.js`, `contributorInfo` contains the following information
![image](https://user-images.githubusercontent.com/86666889/143261993-cc9eaffb-463b-40d0-83e2-826c56e441b6.png)

We have to test if the information of `_previousDataValues` changes when logging or when updating the database.
