### ISSUE TITLE
Check if the github_access_token changed

### ISSUE THREAD

**Issue by Ovifer13** [setlife-network/trinary#580]
When a user logs in check if the `github_access_token`  is different from the one stored in the database,
If it's different from the one given by GitHub we have to update the `github_access_token` stored in the database for the new one.

**Comment by sofiaromorales** [comment]
![Screen Shot 2022-01-04 at 4 00 55 PM](https://user-images.githubusercontent.com/49292858/148116713-04af49c5-a73b-47b0-aa50-0ddb2aaad378.png)

**Comment by sofiaromorales** [comment]
GitHub access token changes every time the user logs in

**Comment by otech47** [comment]
Original intention for this was as a guess to fix an unusual bug that wasn't reproducing consistently
