### ISSUE TITLE
Styling updates to Add Project Page

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#592]
On Add Project page

- Align grey numbered circles with the label (Link the Github Project) - remove margin-bottom on numbered circle fixes this
- Add small margin between Project name and Toggl URL in Step 2

_Originally posted by @otech47 in https://github.com/setlife-network/trinary/discussions/588#discussioncomment-1848314_

**Comment by sofiaromorales** [comment]
- [ ] Align grey numbered circles with the label (Link the Github Project) - remove margin-bottom on numbered circle fixes this

- [ ] Add small margin between Project name and Toggl URL in Step 2
