### ISSUE TITLE
Styling updates to Client and Project tiles

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#594]
On Home Clients List page, Home Projects List page, and Client Detail page (Projects list)

- Client tiles should truncate the client name if it is too long instead of wrapping to a new line
- Project tiles should truncate the project name if it is too long instead of wrapping to a new line

_Originally posted by @otech47 in https://github.com/setlife-network/trinary/discussions/588#discussioncomment-1848323_

**Comment by sofiaromorales** [comment]
https://twitter.com/addyosmani/status/1476440414856962048?s=20
