### ISSUE TITLE
Provide error output for user if they try to use decimals while allocating in trinary 

### ISSUE THREAD

**Issue by ctrocc** [setlife-network/trinary#638]
<img width="773" alt="Screen Shot 2022-05-12 at 8 52 50 AM" src="https://user-images.githubusercontent.com/97178586/168079319-6bf923ce-22de-4a64-8b7f-d7da31d14bf0.png">

**Comment by Ovifer13** [comment]
There is an error happening in the backend when trying to add the allocation
![image](https://user-images.githubusercontent.com/86666889/168654801-d9cb0424-5bbd-4524-af55-cfe2da9000dd.png)
