### ISSUE TITLE
Allow users to edit and delete payments from the Project Detail page

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#646]
- Do not allow deleting if the Payment has Allocations

Show "This payment cannot be deleted because it has linked Allocations" as a tooltip
![Screen Shot 2022-05-20 at 4 22 59 PM](https://user-images.githubusercontent.com/4914611/169548600-9e207b0e-9de7-46f9-95a9-b69c73cd74e0.png)

**Comment by Ovifer13** [comment]
**Tested in Stagging**
- The delete button is disabled when there are allocations.
- If the payment doesn't has allocations the delete button works and the user can proceed to delete a payment.
