### ISSUE TITLE
Build Advanced wallet setup flow UI

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/trinary#760]
https://www.figma.com/file/qgGWXmprU7vTv7guzWzvML/Project-Trinary?node-id=4678-22983&t=anstUNWIhOe0x19U-0

TODO:

- [x]  UI
- [x]  Check that the DB model is in place for storing the data
- [x]  Store data in DB

**Comment by sofiaromorales** [comment]
Blocked by #799

**Comment by otech47** [comment]
### Validating Advanced Wallet

With the host + port + macaroon data we need to use some LND client library... check API docs: https://docs.lightning.engineering/lapps/guides/add-features/connect-to-lnd
