### ISSUE TITLE
Error adding a payment to a Project

### ISSUE THREAD

**Issue by Ovifer13** [setlife-network/trinary#771]
When adding a Payment to a project I get the following error.

![image](https://user-images.githubusercontent.com/86666889/231835397-01a4cc28-5658-4b67-91b9-41b5e21bd6e9.png)

**Comment by sofiaromorales** [comment]
@Ovifer13 how can I test this if I get this error?
![Screen Shot 2023-04-18 at 11 55 07 AM](https://user-images.githubusercontent.com/49292858/232834011-b2bc4b52-9e98-4371-b965-0767732947f1.png)

**Comment by Ovifer13** [comment]
@sofiaromorales you can still access projects from clients
![image](https://user-images.githubusercontent.com/86666889/232834819-8e0e96ba-76b1-47b8-9562-317454a7bce3.png)
