### ISSUE TITLE
Error creating a project in v2

### ISSUE THREAD

**Issue by Ovifer13** [setlife-network/trinary#774]
When creating a project, I get the following error `Error: An error occurred while creating the project`
![image](https://user-images.githubusercontent.com/86666889/231855401-399872c2-238f-44e9-821b-adc72b51469c.png)
![image](https://user-images.githubusercontent.com/86666889/231855443-6042dcf8-f7a4-4de0-9870-a3bb2f6770ca.png)
2

**Comment by Ovifer13** [comment]
**Update**
I was trying to create a project that already exists, would be good to get an error saying that the project already exists

**Comment by sofiaromorales** [comment]
Closing this since and replacing it for #783
