### ISSUE TITLE
Deploy UIv2 to Heroku

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/trinary#790]

**Comment by Ovifer13** [comment]
@sofiaromorales This should be blocked till #786  is merged?

**Comment by sofiaromorales** [comment]
I'm taking care of this one, I forgot to assign myself

**Comment by sofiaromorales** [comment]
https://trinary-staging.setlife.tech/build-v1 -> UIv1
https://trinary-staging.setlife.tech -> UIv2
