### ISSUE TITLE
Implement Send Payment to Contributors API

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/trinary#812]
When clicking on `Send bonuses` (https://www.figma.com/file/qgGWXmprU7vTv7guzWzvML/Project-Trinary?type=design&node-id=4037-12961), the amount in sats must be sent to the selected contributors from the list.

Implement the backend needed to send the money from the advanced wallet of the logged user to the set-up wallets of the selected contributors. If a contributor has a simple and advanced wallet setup use the advanced info to make the payment.

From the UI I should be able to make an API call similar to this:
```js
sendBonuses(amount: (sats), contributors: [(contributorId)]) {
 totalAmountSent
}
```

There might be some implementation in place already since Rishab was working on this last year, before coding take a moment to look at the codebase and understand the state of things.

**Comment by sofiaromorales** [comment]
@Ovifer13 description updated, let me know if you have any questions

**Comment by Ovifer13** [comment]
https://www.npmjs.com/package/bitcoin-transaction
https://lightning.engineering/api-docs/api/lnd/lightning/add-invoice

**Comment by Ovifer13** [comment]
https://docs.btcpayserver.org/FAQ/LightningNetwork/#how-to-change-from-c-lightning-to-lnd-or-vice-versa
