### ISSUE TITLE
Build API query to transform USD to SATS

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/trinary#821]
When sending bonuses the amount will be displayed in USD, but the confirmation will be in SATS, so it's necessary to build a mutation that given a USD amount returns the SATS amount

**Comment by Ovifer13** [comment]
@sofiaromorales this mutation has to be inside the `Payments` resolver?

**Comment by sofiaromorales** [comment]
Where you think is most appropriate, payments sound good
